// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef CHROME_BROWSER_THEMES_CROSS_DEVICE_CROSS_DEVICE_THEME_TRACKER_DESKTOP_H_
#define CHROME_BROWSER_THEMES_CROSS_DEVICE_CROSS_DEVICE_THEME_TRACKER_DESKTOP_H_

#include <memory>

#include "base/functional/callback.h"
#include "base/memory/weak_ptr.h"
#include "components/sync/protocol/theme_android_specifics.pb.h"
#include "components/sync/protocol/theme_ios_specifics.pb.h"
#include "components/sync/protocol/theme_specifics.pb.h"
#include "components/themes/cross_device/cross_device_theme_sync_bridge.h"
#include "components/themes/cross_device/cross_device_theme_tracker.h"
#include "components/version_info/channel.h"

namespace syncer {
class DataTypeControllerDelegate;
}  // namespace syncer

namespace themes {

template <>
struct ThemeComparer<sync_pb::ThemeSpecifics> {
  static bool Equals(const sync_pb::ThemeSpecifics& lhs,
                     const sync_pb::ThemeSpecifics& rhs) {
    if (lhs.has_use_custom_theme() != rhs.has_use_custom_theme()) {
      return false;
    }
    if (lhs.has_use_custom_theme() &&
        lhs.use_custom_theme() != rhs.use_custom_theme()) {
      return false;
    }

    if (lhs.has_use_system_theme_by_default() !=
        rhs.has_use_system_theme_by_default()) {
      return false;
    }
    if (lhs.has_use_system_theme_by_default() &&
        lhs.use_system_theme_by_default() !=
            rhs.use_system_theme_by_default()) {
      return false;
    }

    if (lhs.has_custom_theme_name() != rhs.has_custom_theme_name()) {
      return false;
    }
    if (lhs.has_custom_theme_name() &&
        lhs.custom_theme_name() != rhs.custom_theme_name()) {
      return false;
    }

    if (lhs.has_custom_theme_id() != rhs.has_custom_theme_id()) {
      return false;
    }
    if (lhs.has_custom_theme_id() &&
        lhs.custom_theme_id() != rhs.custom_theme_id()) {
      return false;
    }

    if (lhs.has_custom_theme_update_url() !=
        rhs.has_custom_theme_update_url()) {
      return false;
    }
    if (lhs.has_custom_theme_update_url() &&
        lhs.custom_theme_update_url() != rhs.custom_theme_update_url()) {
      return false;
    }

    if (lhs.has_browser_color_scheme() != rhs.has_browser_color_scheme()) {
      return false;
    }
    if (lhs.has_browser_color_scheme() &&
        lhs.browser_color_scheme() != rhs.browser_color_scheme()) {
      return false;
    }

    if (lhs.color_case() != rhs.color_case()) {
      return false;
    }
    switch (lhs.color_case()) {
      case sync_pb::ThemeSpecifics::kAutogeneratedColorTheme:
        if (lhs.autogenerated_color_theme().color() !=
            rhs.autogenerated_color_theme().color()) {
          return false;
        }
        break;
      case sync_pb::ThemeSpecifics::kUserColorTheme:
        if (!Equals(lhs.user_color_theme(), rhs.user_color_theme())) {
          return false;
        }
        break;
      case sync_pb::ThemeSpecifics::kGrayscaleThemeEnabled:
        break;
      case sync_pb::ThemeSpecifics::COLOR_NOT_SET:
        break;
    }

    if (lhs.has_ntp_background() != rhs.has_ntp_background()) {
      return false;
    }
    if (lhs.has_ntp_background() &&
        !Equals(lhs.ntp_background(), rhs.ntp_background())) {
      return false;
    }

    return true;
  }

 private:
  static bool Equals(const sync_pb::UserColorTheme& lhs,
                     const sync_pb::UserColorTheme& rhs) {
    if (lhs.has_color() != rhs.has_color()) {
      return false;
    }
    if (lhs.has_color() && lhs.color() != rhs.color()) {
      return false;
    }
    if (lhs.has_browser_color_variant() != rhs.has_browser_color_variant()) {
      return false;
    }
    if (lhs.has_browser_color_variant() &&
        lhs.browser_color_variant() != rhs.browser_color_variant()) {
      return false;
    }
    return true;
  }

  static bool Equals(const sync_pb::NtpCustomBackground& lhs,
                     const sync_pb::NtpCustomBackground& rhs) {
    if (lhs.has_url() != rhs.has_url()) {
      return false;
    }
    if (lhs.has_url() && lhs.url() != rhs.url()) {
      return false;
    }
    if (lhs.has_attribution_line_1() != rhs.has_attribution_line_1()) {
      return false;
    }
    if (lhs.has_attribution_line_1() &&
        lhs.attribution_line_1() != rhs.attribution_line_1()) {
      return false;
    }
    if (lhs.has_attribution_line_2() != rhs.has_attribution_line_2()) {
      return false;
    }
    if (lhs.has_attribution_line_2() &&
        lhs.attribution_line_2() != rhs.attribution_line_2()) {
      return false;
    }
    if (lhs.has_attribution_action_url() != rhs.has_attribution_action_url()) {
      return false;
    }
    if (lhs.has_attribution_action_url() &&
        lhs.attribution_action_url() != rhs.attribution_action_url()) {
      return false;
    }
    if (lhs.has_collection_id() != rhs.has_collection_id()) {
      return false;
    }
    if (lhs.has_collection_id() && lhs.collection_id() != rhs.collection_id()) {
      return false;
    }
    if (lhs.has_resume_token() != rhs.has_resume_token()) {
      return false;
    }
    if (lhs.has_resume_token() && lhs.resume_token() != rhs.resume_token()) {
      return false;
    }
    if (lhs.has_refresh_timestamp_unix_epoch_seconds() !=
        rhs.has_refresh_timestamp_unix_epoch_seconds()) {
      return false;
    }
    if (lhs.has_refresh_timestamp_unix_epoch_seconds() &&
        lhs.refresh_timestamp_unix_epoch_seconds() !=
            rhs.refresh_timestamp_unix_epoch_seconds()) {
      return false;
    }
    if (lhs.has_main_color() != rhs.has_main_color()) {
      return false;
    }
    if (lhs.has_main_color() && lhs.main_color() != rhs.main_color()) {
      return false;
    }
    return true;
  }
};

DeviceThemeInfo<sync_pb::ThemeSpecifics> TranslateAndroid(
    const sync_pb::ThemeAndroidSpecifics& android_specifics);

DeviceThemeInfo<sync_pb::ThemeSpecifics> TranslateIos(
    const sync_pb::ThemeIosSpecifics& ios_specifics);

class CrossDeviceThemeTrackerDesktop
    : public CrossDeviceThemeTracker<sync_pb::ThemeSpecifics> {
 public:
  using AndroidBridge =
      CrossDeviceThemeSyncBridge<sync_pb::ThemeAndroidSpecifics,
                                 sync_pb::ThemeSpecifics>;
  using IosBridge = CrossDeviceThemeSyncBridge<sync_pb::ThemeIosSpecifics,
                                               sync_pb::ThemeSpecifics>;

  using AndroidBridgeFactory =
      base::OnceCallback<std::unique_ptr<AndroidBridge>(
          CrossDeviceThemeTrackerDesktop*)>;
  using IosBridgeFactory = base::OnceCallback<std::unique_ptr<IosBridge>(
      CrossDeviceThemeTrackerDesktop*)>;

  using CrossDeviceThemeTracker<sync_pb::ThemeSpecifics>::UpdateThemeInfo;
  using CrossDeviceThemeTracker<sync_pb::ThemeSpecifics>::RemoveThemeInfo;

  CrossDeviceThemeTrackerDesktop(syncer::DeviceInfoTracker* device_info_tracker,
                                 AndroidBridgeFactory android_bridge_factory,
                                 IosBridgeFactory ios_bridge_factory);

  CrossDeviceThemeTrackerDesktop(const CrossDeviceThemeTrackerDesktop&) =
      delete;
  CrossDeviceThemeTrackerDesktop& operator=(
      const CrossDeviceThemeTrackerDesktop&) = delete;

  ~CrossDeviceThemeTrackerDesktop() override;

  base::WeakPtr<syncer::DataTypeControllerDelegate> GetAndroidSyncDelegate();
  base::WeakPtr<syncer::DataTypeControllerDelegate> GetIosSyncDelegate();

 private:
  std::unique_ptr<CrossDeviceThemeSyncBridge<sync_pb::ThemeAndroidSpecifics,
                                             sync_pb::ThemeSpecifics>>
      android_bridge_;
  std::unique_ptr<CrossDeviceThemeSyncBridge<sync_pb::ThemeIosSpecifics,
                                             sync_pb::ThemeSpecifics>>
      ios_bridge_;
};

}  // namespace themes

#endif  // CHROME_BROWSER_THEMES_CROSS_DEVICE_CROSS_DEVICE_THEME_TRACKER_DESKTOP_H_
