name: rolling/build-pc

on:
  # discussion_comment:
  # issue_comment:
  # pull_request_review_comment:
  # pull_request_review:
  pull_request:
    branches:
    - neva-main-rolling*
  workflow_dispatch:

jobs:
  build:
    name: rolling/build-pc
    if: github.event_name == 'workflow_dispatch'
    runs-on: self-hosted
    env:
      CI_TOKEN: ${{ secrets.CI_TOKEN }}

    steps:
      - uses: actions/checkout@v6
        with:
          repository: nevaoss/ci
          ref: main
      - name: Run PC builder (rolling settings & environment)
        run: |
          ./rolling/build-pc.py
