name: test-webos-bvt

on:
  # discussion_comment:
  # issue_comment:
  # pull_request_review_comment:
  # pull_request_review:
  # pull_request:
  workflow_dispatch:
  
jobs:
  test-webos-bvt:
    name: test-webos-bvt
    if: ${{ ! startsWith(github.ref_name, 'neva-main-rolling') }}
    runs-on: self-hosted
    env:
      CI_TOKEN: ${{ secrets.CI_TOKEN }}

    steps:
      - uses: actions/checkout@v6
        with:
          repository: nevaoss/ci
          ref: main
      - name: Run BVT tests for webOS/OSE target
        run: |
          ./test-webos-bvt.py

  rolling-test-webos-bvt:
    name: rolling-test-webos-bvt
    if: ${{ startsWith(github.ref_name, 'neva-main-rolling') }}
    runs-on: self-hosted
    env:
      CI_TOKEN: ${{ secrets.CI_TOKEN }}

    steps:
      - uses: actions/checkout@v6
        with:
          repository: nevaoss/ci
          ref: main
      - name: Run BVT tests for webOS/OSE target
        run: |
          ./rolling/test-webos-bvt.py
